version: "3"
services:
  app:
    build:
      context: ./php
      args:
        - TZ=${TZ}
    volumes:
      - ${APP_PATH}:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TESTING_HOST=db-testing
      - DB_TESTING_DATABASE=${DB_TESTING_DATABASE}
      - DB_TESTING_USERNAME=${DB_TESTING_USERNAME}
      - DB_TESTING_PASSWORD=${DB_TESTING_PASSWORD}
      - TZ=${TZ}
  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${APP_PATH}:/app
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./db/log:/var/log/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
  db-testing:
    image: mysql:8.0
    volumes:
      - db-testing-store:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_TESTING_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_TESTING_PASSWORD}
      - TZ=${TZ}
    ports:
      - ${DB_TESTING_PORT}:3306
volumes:
  db-store:
  db-testing-store:
